image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - vscjava.vscode-java-test@0.28.1:Vq5tqFnbBv8CzIO03Hf19A==
    - vscjava.vscode-maven@0.21.2:tFEkt2FqLujaNTLU5AmRiQ==
    - vscode-icons-team.vscode-icons@11.2.0:wzrAlW1rFgqS/LpeO/sU2Q==