image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080 # pgAdmin 4
    onOpen: open-browser
  - port: 5432 # PostgreSQL
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      sudo docker-up &
      mkdir -p /workspace/pgadmin-data
      sudo chown -R 5050:5050 /workspace/pgadmin-data
      sleep 5
    init: docker-compose up --no-start
    command: docker-compose up

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
    - vscode-icons-team.vscode-icons
    - coenraads.bracket-pair-colorizer
    - vscodevim.vim
    - wakatime.vscode-wakatime
    - asciidoctor.asciidoctor-vscode
    - sonarsource.sonarlint-vscode
    - redhat.fabric8-analytics
    - redhat.vscode-xml
    - dotjoshjohnson.xml
    - eamodio.gitlens
