version: "3.7"
services:
  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /workspace/db-data:/var/lib/postgresql/data
      - /workspace/uniciv-pos-java-jdbc/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: filipe.fsn@uniciv.edu.br
      PGADMIN_DEFAULT_PASSWORD: uniciv
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - /workspace/pgadmin-data:/var/lib/pgadmin
      - /tmp:/tmp
      - /workspace:/workspace
      - /workspace/uniciv-pos-java-jdbc/pgadmin4/servers.json:/pgadmin4/servers.json
    links:
      - "db:pgsql-server"
